In [ ]:
from google.colab import drive

In [ ]:
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os

MODEL_DIR = "/content/drive/MyDrive/RAG_Project/models"

print(os.listdir(MODEL_DIR))

['prometheus-7b-v2.0', 'bge-base-en-v1.5', 'prometheus-7b-v2.0-GGUF']

In [ ]:
MODEL_DIR

'/content/drive/MyDrive/RAG_Project/models'

In [ ]:
!pip install -q huggingface_hub

In [ ]:
from huggingface_hub import snapshot_download

snapshot_download(
    repo_id="BAAI/bge-base-en-v1.5",
    local_dir="/content/drive/MyDrive/RAG_Project/models/bge-base-en-v1.5"
)

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 14 files:   0%|          | 0/14 [00:00<?, ?it/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

'/content/drive/MyDrive/RAG_Project/models/bge-base-en-v1.5'

In [ ]:
import torch

if torch.cuda.is_available():
    print(f"✅ GPU is active: {torch.cuda.get_device_name(0)}")
else:
    print(" CPU is active (No GPU detected)")

✅ GPU is active: Tesla T4

In [ ]:
from huggingface_hub import snapshot_download

snapshot_download(
    repo_id="prometheus-eval/prometheus-7b-v2.0",
    local_dir="/content/drive/MyDrive/RAG_Project/models/prometheus-7b-v2.0"
)

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 18 files:   0%|          | 0/18 [00:00<?, ?it/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

'/content/drive/MyDrive/RAG_Project/models/prometheus-7b-v2.0'

In [ ]:
!du -sh "/content/drive/MyDrive/RAG_Project/models/prometheus-7b-v2.0"

14G	/content/drive/MyDrive/RAG_Project/models/prometheus-7b-v2.0

# Embedding Model

In [ ]:
from huggingface_hub import snapshot_download

snapshot_download(
    repo_id="BAAI/bge-base-en-v1.5",
    local_dir="/content/drive/MyDrive/RAG_Project/models/bge-base-en-v1.5"
)

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 14 files:   0%|          | 0/14 [00:00<?, ?it/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

'/content/drive/MyDrive/RAG_Project/models/bge-base-en-v1.5'

# Work Starts From Here

In [ ]:
!pip install -q ragas==0.4.3
!pip install -q langchain-huggingface sentence-transformers
!pip install -q openai huggingface_hub

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 466.5/466.5 kB 5.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 1.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 269.4/269.4 kB 8.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 26.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.3/127.3 kB 4.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 572.0/572.0 kB 14.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 39.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 353.2/353.2 kB 14.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 24.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.4/69.4 kB 3.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 3.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.7/135.7 kB 3.5 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.

In [ ]:
!pip install -q requests==2.34.2

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.

In [ ]:
!pip install -q jedi

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 22.6 MB/s eta 0:00:00

In [ ]:
import ragas
import langchain
import requests

print("Ragas:", ragas.__version__)
print("LangChain:", langchain.__version__)
print("Requests:", requests.__version__)

ModuleNotFoundError: No module named 'langchain_community.chat_models.vertexai'

In [ ]:
!pip install -q "langchain-community==0.4.1"

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 17.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 4.7 MB/s eta 0:00:00

In [ ]:
import ragas

print(ragas.__version__)

0.4.3

In [ ]:
from google.colab import drive

drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
PROMETHEUS_PATH = "/content/drive/MyDrive/RAG_Project/models/prometheus-7b-v2.0"
BGE_PATH = "/content/drive/MyDrive/RAG_Project/models/bge-base-en-v1.5"

In [ ]:
import os

print("Prometheus:", os.path.exists(PROMETHEUS_PATH))
print("BGE:", os.path.exists(BGE_PATH))

Prometheus: True
BGE: True

In [ ]:
!du -sh "$PROMETHEUS_PATH"

14G	/content/drive/MyDrive/RAG_Project/models/prometheus-7b-v2.0

In [ ]:
GGUF_PATH = "/content/drive/MyDrive/RAG_Project/models/prometheus-7b-v2.0-GGUF"

In [ ]:
from huggingface_hub import snapshot_download

snapshot_download(
    repo_id="prometheus-eval/prometheus-7b-v2.0-GGUF",
    local_dir=GGUF_PATH,
    allow_patterns=["prometheus-7b-v2.0.Q4_K_M.gguf"]
)

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 1 files:   0%|          | 0/1 [00:00<?, ?it/s]

'/content/drive/MyDrive/RAG_Project/models/prometheus-7b-v2.0-GGUF'

In [ ]:
!find "$GGUF_PATH" -type f

/content/drive/MyDrive/RAG_Project/models/prometheus-7b-v2.0-GGUF/.cache/huggingface/trees/1d1dbdec4c0a5b479b11642669d5ae6514137e96.json
/content/drive/MyDrive/RAG_Project/models/prometheus-7b-v2.0-GGUF/.cache/huggingface/CACHEDIR.TAG
/content/drive/MyDrive/RAG_Project/models/prometheus-7b-v2.0-GGUF/.cache/huggingface/.gitignore
/content/drive/MyDrive/RAG_Project/models/prometheus-7b-v2.0-GGUF/.cache/huggingface/download/prometheus-7b-v2.0.Q4_K_M.gguf.lock
/content/drive/MyDrive/RAG_Project/models/prometheus-7b-v2.0-GGUF/.cache/huggingface/download/prometheus-7b-v2.0.Q4_K_M.gguf.metadata
/content/drive/MyDrive/RAG_Project/models/prometheus-7b-v2.0-GGUF/prometheus-7b-v2.0.Q4_K_M.gguf

In [ ]:
!du -sh "$GGUF_PATH"

4.1G	/content/drive/MyDrive/RAG_Project/models/prometheus-7b-v2.0-GGUF

In [ ]:
import sys
import subprocess

print("Python:", sys.version)

!nvidia-smi

Python: 3.13.15 (main, Aug  6 2026, 11:06:22) [GCC 13.3.0]
Wed Sep 23 17:22:00 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   42C    P8             10W /   70W |       3MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [ ]:
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2026 NVIDIA Corporation
Built on Tue_Jun_09_02:43:40_PM_PDT_2026
Cuda compilation tools, release 13.3, V13.3.73
Build cuda_13.3.r13.3/compiler.38244171_0

In [ ]:
!CMAKE_ARGS="-DGGML_CUDA=on" FORCE_CMAKE=1 pip install -q llama-cpp-python

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.9/74.9 MB 11.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
  Building wheel for llama-cpp-python (pyproject.toml) ... canceled
ERROR: Operation cancelled by user
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/dist-packages/pip/_internal/cli/base_command.py", line 179, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/local/lib/python3.13/dist-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.13/dist-packages/pip/_internal/commands/install.py", line 423, in run
    _, build_failures = build(
                        ~~~~~^
        reqs_to_build,
        ^^^^^^^^^^^^^^
    ...<3 lines>...
        global_options=global_options,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/pip/_internal/wheel_builder.py", line 319, in build
    wheel_file = _build_one(
        req,
    ...<4 lines>...
        req.editable and req.permit_editable_wheels,
    )
  File "/usr/local/lib/python3.13/dist-packages/pip/_internal/wheel_builder.py", line 193, in _build_one
    wheel_path = _build_one_inside_env(
        req, output_dir, build_options, global_options, editable
    )
  File "/usr/local/lib/python3.13/dist-packages/pip/_internal/wheel_builder.py", line 233, in _build_one_inside_env
    wheel_path = build_wheel_pep517(
        name=req.name,
    ...<2 lines>...
        tempd=temp_dir.path,
    )
  File "/usr/local/lib/python3.13/dist-packages/pip/_internal/operations/build/wheel.py", line 30, in build_wheel_pep517
    wheel_name = backend.build_wheel(
        tempd,
        metadata_directory=metadata_directory,
    )
  File "/usr/local/lib/python3.13/dist-packages/pip/_internal/utils/misc.py", line 682, in build_wheel
    return super().build_wheel(
           ~~~~~~~~~~~~~~~~~~~^
        wheel_directory, config_settings=cs, metadata_directory=metadata_directory
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/pip/_vendor/pyproject_hooks/_impl.py", line 209, in build_wheel
    return self._call_hook('build_wheel', {
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
        'wheel_directory': abspath(wheel_directory),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        'config_settings': config_settings,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        'metadata_directory': metadata_directory,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    })
    ^^
  File "/usr/local/lib/python3.13/dist-packages/pip/_vendor/pyproject_hooks/_impl.py", line 311, in _call_hook
    self._subprocess_runner(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        [python, abspath(str(script)), hook_name, td],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        cwd=self.source_dir,
        ^^^^^^^^^^^^^^^^^^^^
        extra_environ=extra_environ
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/pip/_internal/utils/subprocess.py", line 237, in runner
    call_subprocess(
    ~~~~~~~~~~~~~~~^
        cmd,
        ^^^^
    ...<3 lines>...
        spinner=spinner,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/pip/_internal/utils/subprocess.py", line 151, in call_subprocess
    line: str = proc.stdout.readline()
                ~~~~~~~~~~~~~~~~~~~~^^
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 10, in <module>
    sys.exit(main())
             ~~~~^^
  File "/usr/local/lib/python3.13/dist-packages/pip/_internal/cli/main.py", line 80, in main
    return command.main(cmd_args)
           ~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/pip/_internal/cli/base_command.py", line 100, in main
    return self._main(args)
           ~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/pip/_internal/cli/base_command.py", line 232, in _main
    return run(options, args)
  File "/usr/local/lib/python3.13/dist-packages/pip/_internal/cli/base_command.py", line 215, in exc_logging_wrapper
    logger.critical("Operation cancelled by user")
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/logging/__init__.py", line 1567, in critical
    self._log(CRITICAL, msg, args, **kwargs)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/logging/__init__.py", line 1665, in _log
    self.handle(record)
    ~~~~~~~~~~~^^^^^^^^
  File "/usr/lib/python3.13/logging/__init__.py", line 1681, in handle
    self.callHandlers(record)
    ~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/usr/lib/python3.13/logging/__init__.py", line 1741, in callHandlers
    hdlr.handle(record)
    ~~~~~~~~~~~^^^^^^^^
  File "/usr/lib/python3.13/logging/__init__.py", line 1027, in handle
    self.emit(record)
    ~~~~~~~~~^^^^^^^^
  File "/usr/lib/python3.13/logging/handlers.py", line 81, in emit
    logging.FileHandler.emit(self, record)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/logging/__init__.py", line 1265, in emit
    StreamHandler.emit(self, record)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/logging/__init__.py", line 1151, in emit
    msg = self.format(record)
  File "/usr/lib/python3.13/logging/__init__.py", line 999, in format
    return fmt.format(record)
           ~~~~~~~~~~^^^^^^^^
  File "/usr/local/lib/python3.13/dist-packages/pip/_internal/utils/logging.py", line 118, in format
    prefix = f"{self.formatTime(record)} "
                ~~~~~~~~~~~~~~~^^^^^^^^
  File "/usr/lib/python3.13/logging/__init__.py", line 649, in formatTime
    ct = self.converter(record.created)
KeyboardInterrupt
^C

In [ ]:
!pip uninstall -y llama-cpp-python

WARNING: Skipping llama-cpp-python as it is not installed.

In [ ]:
!pip install -q --no-deps https://github.com/JamePeng/llama-cpp-python/releases/download/v0.3.38-cu130-Basic-linux-20260504/llama_cpp_python-0.3.38+cu130.basic-cp313-cp313-linux_x86_64.whl

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.5/469.5 MB 4.0 MB/s eta 0:00:00

In [ ]:
from llama_cpp import Llama

print("llama-cpp loaded ✅")

llama-cpp loaded ✅

In [ ]:
from llama_cpp import Llama
import os
import shutil
import time

In [ ]:
PROMETHEUS_GGUF = "/content/drive/MyDrive/RAG_Project/models/prometheus-7b-v2.0-GGUF/prometheus-7b-v2.0.Q4_K_M.gguf"

LOCAL_PROMETHEUS = "/content/prometheus-7b-v2.0.Q4_K_M.gguf"

In [ ]:
if not os.path.exists(LOCAL_PROMETHEUS):
    print("Copying model to local storage...")
    shutil.copy2(PROMETHEUS_GGUF, LOCAL_PROMETHEUS)
    print("Copy complete ✅")
else:
    print("Model already exists locally ✅")

Copying model to local storage...
Copy complete ✅

In [ ]:
llm = Llama(
    model_path=LOCAL_PROMETHEUS,
    n_gpu_layers=-1,
    n_ctx=4096,
    verbose=True
)

ggml_cuda_init: found 1 CUDA devices (Total VRAM: 14912 MiB):
  Device 0: Tesla T4, compute capability 7.5, VMM: yes, VRAM: 14912 MiB
llama_model_load_from_file_impl: using device CUDA0 (Tesla T4) (0000:00:04.0) - 14807 MiB free
llama_model_loader: loaded meta data with 24 key-value pairs and 291 tensors from /content/prometheus-7b-v2.0.Q4_K_M.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = prometheus-7b-v2.0
llama_model_loader: - kv   2:                          llama.block_count u32              = 32
llama_model_loader: - kv   3:                       llama.context_length u32              = 32768
llama_model_loader: - kv   4:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 14336
llama_model_loader: - kv   6:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   7:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv   8:                       llama.rope.freq_base f32              = 1000000.000000
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  10:                          general.file_type u32              = 15
llama_model_loader: - kv  11:                           llama.vocab_size u32              = 32000
llama_model_loader: - kv  12:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv  13:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  14:                         tokenizer.ggml.pre str              = default
llama_model_loader: - kv  15:                      tokenizer.ggml.tokens arr[str,32000]   = ["<unk>", "<s>", "</s>", "<0x00>", "<...
llama_model_loader: - kv  16:                      tokenizer.ggml.scores arr[f32,32000]   = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  17:                  tokenizer.ggml.token_type arr[i32,32000]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv  18:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  19:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  20:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  21:            tokenizer.ggml.padding_token_id u32              = 2
llama_model_loader: - kv  22:                    tokenizer.chat_template str              = {{ bos_token }}{% for message in mess...
llama_model_loader: - kv  23:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type q4_K:  193 tensors
llama_model_loader: - type q6_K:   33 tensors
print_info: file format = GGUF V3 (latest)
print_info: file type   = Q4_K - Medium
print_info: file size   = 4.07 GiB (4.83 BPW)
init_tokenizer: initializing tokenizer for type 1
load: 0 unused tokens
load: control token:      1 '<s>' is not marked as EOG
load: printing all EOG tokens:
load:   - 2 ('</s>')
load: special tokens cache size = 3
load: token to piece cache size = 0.1637 MB
print_info: arch                  = llama
print_info: vocab_only            = 0
print_info: no_alloc              = 0
print_info: n_ctx_train           = 32768
print_info: n_embd                = 4096
print_info: n_embd_inp            = 4096
print_info: n_layer               = 32
print_info: n_head                = 32
print_info: n_head_kv             = 8
print_info: n_rot                 = 128
print_info: n_swa                 = 0
print_info: is_swa_any            = 0
print_info: n_embd_head_k         = 128
print_info: n_embd_head_v         = 128
print_info: n_gqa                 = 4
print_info: n_embd_k_gqa          = 1024
print_info: n_embd_v_gqa          = 1024
print_info: f_norm_eps            = 0.0e+00
print_info: f_norm_rms_eps        = 1.0e-05
print_info: f_clamp_kqv           = 0.0e+00
print_info: f_max_alibi_bias      = 0.0e+00
print_info: f_logit_scale         = 0.0e+00
print_info: f_attn_scale          = 0.0e+00
print_info: n_ff                  = 14336
print_info: n_expert              = 0
print_info: n_expert_used         = 0
print_info: n_expert_groups       = 0
print_info: n_group_used          = 0
print_info: causal attn           = 1
print_info: pooling type          = -1
print_info: rope type             = 0
print_info: rope scaling          = linear
print_info: freq_base_train       = 1000000.0
print_info: freq_scale_train      = 1
print_info: n_ctx_orig_yarn       = 32768
print_info: rope_yarn_log_mul     = 0.0000
print_info: rope_finetuned        = unknown
print_info: model type            = 7B
print_info: model params          = 7.24 B
print_info: general.name          = prometheus-7b-v2.0
print_info: vocab type            = SPM
print_info: n_vocab               = 32000
print_info: n_merges              = 0
print_info: BOS token             = 1 '<s>'
print_info: EOS token             = 2 '</s>'
print_info: UNK token             = 0 '<unk>'
print_info: PAD token             = 2 '</s>'
print_info: LF token              = 13 '<0x0A>'
print_info: EOG token             = 2 '</s>'
print_info: max token length      = 48
load_tensors: loading model tensors, this can take a while... (mmap = true, direct_io = false)
load_tensors: layer   0 assigned to device CUDA0, is_swa = 0
load_tensors: layer   1 assigned to device CUDA0, is_swa = 0
load_tensors: layer   2 assigned to device CUDA0, is_swa = 0
load_tensors: layer   3 assigned to device CUDA0, is_swa = 0
load_tensors: layer   4 assigned to device CUDA0, is_swa = 0
load_tensors: layer   5 assigned to device CUDA0, is_swa = 0
load_tensors: layer   6 assigned to device CUDA0, is_swa = 0
load_tensors: layer   7 assigned to device CUDA0, is_swa = 0
load_tensors: layer   8 assigned to device CUDA0, is_swa = 0
load_tensors: layer   9 assigned to device CUDA0, is_swa = 0
load_tensors: layer  10 assigned to device CUDA0, is_swa = 0
load_tensors: layer  11 assigned to device CUDA0, is_swa = 0
load_tensors: layer  12 assigned to device CUDA0, is_swa = 0
load_tensors: layer  13 assigned to device CUDA0, is_swa = 0
load_tensors: layer  14 assigned to device CUDA0, is_swa = 0
load_tensors: layer  15 assigned to device CUDA0, is_swa = 0
load_tensors: layer  16 assigned to device CUDA0, is_swa = 0
load_tensors: layer  17 assigned to device CUDA0, is_swa = 0
load_tensors: layer  18 assigned to device CUDA0, is_swa = 0
load_tensors: layer  19 assigned to device CUDA0, is_swa = 0
load_tensors: layer  20 assigned to device CUDA0, is_swa = 0
load_tensors: layer  21 assigned to device CUDA0, is_swa = 0
load_tensors: layer  22 assigned to device CUDA0, is_swa = 0
load_tensors: layer  23 assigned to device CUDA0, is_swa = 0
load_tensors: layer  24 assigned to device CUDA0, is_swa = 0
load_tensors: layer  25 assigned to device CUDA0, is_swa = 0
load_tensors: layer  26 assigned to device CUDA0, is_swa = 0
load_tensors: layer  27 assigned to device CUDA0, is_swa = 0
load_tensors: layer  28 assigned to device CUDA0, is_swa = 0
load_tensors: layer  29 assigned to device CUDA0, is_swa = 0
load_tensors: layer  30 assigned to device CUDA0, is_swa = 0
load_tensors: layer  31 assigned to device CUDA0, is_swa = 0
load_tensors: layer  32 assigned to device CUDA0, is_swa = 0
create_tensor: loading tensor token_embd.weight
create_tensor: loading tensor output_norm.weight
create_tensor: loading tensor output.weight
create_tensor: loading tensor blk.0.attn_norm.weight
create_tensor: loading tensor blk.0.attn_q.weight
create_tensor: loading tensor blk.0.attn_k.weight
create_tensor: loading tensor blk.0.attn_v.weight
create_tensor: loading tensor blk.0.attn_output.weight
create_tensor: loading tensor blk.0.ffn_norm.weight
create_tensor: loading tensor blk.0.ffn_gate.weight
create_tensor: loading tensor blk.0.ffn_down.weight
create_tensor: loading tensor blk.0.ffn_up.weight
create_tensor: loading tensor blk.1.attn_norm.weight
create_tensor: loading tensor blk.1.attn_q.weight
create_tensor: loading tensor blk.1.attn_k.weight
create_tensor: loading tensor blk.1.attn_v.weight
create_tensor: loading tensor blk.1.attn_output.weight
create_tensor: loading tensor blk.1.ffn_norm.weight
create_tensor: loading tensor blk.1.ffn_gate.weight
create_tensor: loading tensor blk.1.ffn_down.weight
create_tensor: loading tensor blk.1.ffn_up.weight
create_tensor: loading tensor blk.2.attn_norm.weight
create_tensor: loading tensor blk.2.attn_q.weight
create_tensor: loading tensor blk.2.attn_k.weight
create_tensor: loading tensor blk.2.attn_v.weight
create_tensor: loading tensor blk.2.attn_output.weight
create_tensor: loading tensor blk.2.ffn_norm.weight
create_tensor: loading tensor blk.2.ffn_gate.weight
create_tensor: loading tensor blk.2.ffn_down.weight
create_tensor: loading tensor blk.2.ffn_up.weight
create_tensor: loading tensor blk.3.attn_norm.weight
create_tensor: loading tensor blk.3.attn_q.weight
create_tensor: loading tensor blk.3.attn_k.weight
create_tensor: loading tensor blk.3.attn_v.weight
create_tensor: loading tensor blk.3.attn_output.weight
create_tensor: loading tensor blk.3.ffn_norm.weight
create_tensor: loading tensor blk.3.ffn_gate.weight
create_tensor: loading tensor blk.3.ffn_down.weight
create_tensor: loading tensor blk.3.ffn_up.weight
create_tensor: loading tensor blk.4.attn_norm.weight
create_tensor: loading tensor blk.4.attn_q.weight
create_tensor: loading tensor blk.4.attn_k.weight
create_tensor: loading tensor blk.4.attn_v.weight
create_tensor: loading tensor blk.4.attn_output.weight
create_tensor: loading tensor blk.4.ffn_norm.weight
create_tensor: loading tensor blk.4.ffn_gate.weight
create_tensor: loading tensor blk.4.ffn_down.weight
create_tensor: loading tensor blk.4.ffn_up.weight
create_tensor: loading tensor blk.5.attn_norm.weight
create_tensor: loading tensor blk.5.attn_q.weight
create_tensor: loading tensor blk.5.attn_k.weight
create_tensor: loading tensor blk.5.attn_v.weight
create_tensor: loading tensor blk.5.attn_output.weight
create_tensor: loading tensor blk.5.ffn_norm.weight
create_tensor: loading tensor blk.5.ffn_gate.weight
create_tensor: loading tensor blk.5.ffn_down.weight
create_tensor: loading tensor blk.5.ffn_up.weight
create_tensor: loading tensor blk.6.attn_norm.weight
create_tensor: loading tensor blk.6.attn_q.weight
create_tensor: loading tensor blk.6.attn_k.weight
create_tensor: loading tensor blk.6.attn_v.weight
create_tensor: loading tensor blk.6.attn_output.weight
create_tensor: loading tensor blk.6.ffn_norm.weight
create_tensor: loading tensor blk.6.ffn_gate.weight
create_tensor: loading tensor blk.6.ffn_down.weight
create_tensor: loading tensor blk.6.ffn_up.weight
create_tensor: loading tensor blk.7.attn_norm.weight
create_tensor: loading tensor blk.7.attn_q.weight
create_tensor: loading tensor blk.7.attn_k.weight
create_tensor: loading tensor blk.7.attn_v.weight
create_tensor: loading tensor blk.7.attn_output.weight
create_tensor: loading tensor blk.7.ffn_norm.weight
create_tensor: loading tensor blk.7.ffn_gate.weight
create_tensor: loading tensor blk.7.ffn_down.weight
create_tensor: loading tensor blk.7.ffn_up.weight
create_tensor: loading tensor blk.8.attn_norm.weight
create_tensor: loading tensor blk.8.attn_q.weight
create_tensor: loading tensor blk.8.attn_k.weight
create_tensor: loading tensor blk.8.attn_v.weight
create_tensor: loading tensor blk.8.attn_output.weight
create_tensor: loading tensor blk.8.ffn_norm.weight
create_tensor: loading tensor blk.8.ffn_gate.weight
create_tensor: loading tensor blk.8.ffn_down.weight
create_tensor: loading tensor blk.8.ffn_up.weight
create_tensor: loading tensor blk.9.attn_norm.weight
create_tensor: loading tensor blk.9.attn_q.weight
create_tensor: loading tensor blk.9.attn_k.weight
create_tensor: loading tensor blk.9.attn_v.weight
create_tensor: loading tensor blk.9.attn_output.weight
create_tensor: loading tensor blk.9.ffn_norm.weight
create_tensor: loading tensor blk.9.ffn_gate.weight
create_tensor: loading tensor blk.9.ffn_down.weight
create_tensor: loading tensor blk.9.ffn_up.weight
create_tensor: loading tensor blk.10.attn_norm.weight
create_tensor: loading tensor blk.10.attn_q.weight
create_tensor: loading tensor blk.10.attn_k.weight
create_tensor: loading tensor blk.10.attn_v.weight
create_tensor: loading tensor blk.10.attn_output.weight
create_tensor: loading tensor blk.10.ffn_norm.weight
create_tensor: loading tensor blk.10.ffn_gate.weight
create_tensor: loading tensor blk.10.ffn_down.weight
create_tensor: loading tensor blk.10.ffn_up.weight
create_tensor: loading tensor blk.11.attn_norm.weight
create_tensor: loading tensor blk.11.attn_q.weight
create_tensor: loading tensor blk.11.attn_k.weight
create_tensor: loading tensor blk.11.attn_v.weight
create_tensor: loading tensor blk.11.attn_output.weight
create_tensor: loading tensor blk.11.ffn_norm.weight
create_tensor: loading tensor blk.11.ffn_gate.weight
create_tensor: loading tensor blk.11.ffn_down.weight
create_tensor: loading tensor blk.11.ffn_up.weight
create_tensor: loading tensor blk.12.attn_norm.weight
create_tensor: loading tensor blk.12.attn_q.weight
create_tensor: loading tensor blk.12.attn_k.weight
create_tensor: loading tensor blk.12.attn_v.weight
create_tensor: loading tensor blk.12.attn_output.weight
create_tensor: loading tensor blk.12.ffn_norm.weight
create_tensor: loading tensor blk.12.ffn_gate.weight
create_tensor: loading tensor blk.12.ffn_down.weight
create_tensor: loading tensor blk.12.ffn_up.weight
create_tensor: loading tensor blk.13.attn_norm.weight
create_tensor: loading tensor blk.13.attn_q.weight
create_tensor: loading tensor blk.13.attn_k.weight
create_tensor: loading tensor blk.13.attn_v.weight
create_tensor: loading tensor blk.13.attn_output.weight
create_tensor: loading tensor blk.13.ffn_norm.weight
create_tensor: loading tensor blk.13.ffn_gate.weight
create_tensor: loading tensor blk.13.ffn_down.weight
create_tensor: loading tensor blk.13.ffn_up.weight
create_tensor: loading tensor blk.14.attn_norm.weight
create_tensor: loading tensor blk.14.attn_q.weight
create_tensor: loading tensor blk.14.attn_k.weight
create_tensor: loading tensor blk.14.attn_v.weight
create_tensor: loading tensor blk.14.attn_output.weight
create_tensor: loading tensor blk.14.ffn_norm.weight
create_tensor: loading tensor blk.14.ffn_gate.weight
create_tensor: loading tensor blk.14.ffn_down.weight
create_tensor: loading tensor blk.14.ffn_up.weight
create_tensor: loading tensor blk.15.attn_norm.weight
create_tensor: loading tensor blk.15.attn_q.weight
create_tensor: loading tensor blk.15.attn_k.weight
create_tensor: loading tensor blk.15.attn_v.weight
create_tensor: loading tensor blk.15.attn_output.weight
create_tensor: loading tensor blk.15.ffn_norm.weight
create_tensor: loading tensor blk.15.ffn_gate.weight
create_tensor: loading tensor blk.15.ffn_down.weight
create_tensor: loading tensor blk.15.ffn_up.weight
create_tensor: loading tensor blk.16.attn_norm.weight
create_tensor: loading tensor blk.16.attn_q.weight
create_tensor: loading tensor blk.16.attn_k.weight
create_tensor: loading tensor blk.16.attn_v.weight
create_tensor: loading tensor blk.16.attn_output.weight
create_tensor: loading tensor blk.16.ffn_norm.weight
create_tensor: loading tensor blk.16.ffn_gate.weight
create_tensor: loading tensor blk.16.ffn_down.weight
create_tensor: loading tensor blk.16.ffn_up.weight
create_tensor: loading tensor blk.17.attn_norm.weight
create_tensor: loading tensor blk.17.attn_q.weight
create_tensor: loading tensor blk.17.attn_k.weight
create_tensor: loading tensor blk.17.attn_v.weight
create_tensor: loading tensor blk.17.attn_output.weight
create_tensor: loading tensor blk.17.ffn_norm.weight
create_tensor: loading tensor blk.17.ffn_gate.weight
create_tensor: loading tensor blk.17.ffn_down.weight
create_tensor: loading tensor blk.17.ffn_up.weight
create_tensor: loading tensor blk.18.attn_norm.weight
create_tensor: loading tensor blk.18.attn_q.weight
create_tensor: loading tensor blk.18.attn_k.weight
create_tensor: loading tensor blk.18.attn_v.weight
create_tensor: loading tensor blk.18.attn_output.weight
create_tensor: loading tensor blk.18.ffn_norm.weight
create_tensor: loading tensor blk.18.ffn_gate.weight
create_tensor: loading tensor blk.18.ffn_down.weight
create_tensor: loading tensor blk.18.ffn_up.weight
create_tensor: loading tensor blk.19.attn_norm.weight
create_tensor: loading tensor blk.19.attn_q.weight
create_tensor: loading tensor blk.19.attn_k.weight
create_tensor: loading tensor blk.19.attn_v.weight
create_tensor: loading tensor blk.19.attn_output.weight
create_tensor: loading tensor blk.19.ffn_norm.weight
create_tensor: loading tensor blk.19.ffn_gate.weight
create_tensor: loading tensor blk.19.ffn_down.weight
create_tensor: loading tensor blk.19.ffn_up.weight
create_tensor: loading tensor blk.20.attn_norm.weight
create_tensor: loading tensor blk.20.attn_q.weight
create_tensor: loading tensor blk.20.attn_k.weight
create_tensor: loading tensor blk.20.attn_v.weight
create_tensor: loading tensor blk.20.attn_output.weight
create_tensor: loading tensor blk.20.ffn_norm.weight
create_tensor: loading tensor blk.20.ffn_gate.weight
create_tensor: loading tensor blk.20.ffn_down.weight
create_tensor: loading tensor blk.20.ffn_up.weight
create_tensor: loading tensor blk.21.attn_norm.weight
create_tensor: loading tensor blk.21.attn_q.weight
create_tensor: loading tensor blk.21.attn_k.weight
create_tensor: loading tensor blk.21.attn_v.weight
create_tensor: loading tensor blk.21.attn_output.weight
create_tensor: loading tensor blk.21.ffn_norm.weight
create_tensor: loading tensor blk.21.ffn_gate.weight
create_tensor: loading tensor blk.21.ffn_down.weight
create_tensor: loading tensor blk.21.ffn_up.weight
create_tensor: loading tensor blk.22.attn_norm.weight
create_tensor: loading tensor blk.22.attn_q.weight
create_tensor: loading tensor blk.22.attn_k.weight
create_tensor: loading tensor blk.22.attn_v.weight
create_tensor: loading tensor blk.22.attn_output.weight
create_tensor: loading tensor blk.22.ffn_norm.weight
create_tensor: loading tensor blk.22.ffn_gate.weight
create_tensor: loading tensor blk.22.ffn_down.weight
create_tensor: loading tensor blk.22.ffn_up.weight
create_tensor: loading tensor blk.23.attn_norm.weight
create_tensor: loading tensor blk.23.attn_q.weight
create_tensor: loading tensor blk.23.attn_k.weight
create_tensor: loading tensor blk.23.attn_v.weight
create_tensor: loading tensor blk.23.attn_output.weight
create_tensor: loading tensor blk.23.ffn_norm.weight
create_tensor: loading tensor blk.23.ffn_gate.weight
create_tensor: loading tensor blk.23.ffn_down.weight
create_tensor: loading tensor blk.23.ffn_up.weight
create_tensor: loading tensor blk.24.attn_norm.weight
create_tensor: loading tensor blk.24.attn_q.weight
create_tensor: loading tensor blk.24.attn_k.weight
create_tensor: loading tensor blk.24.attn_v.weight
create_tensor: loading tensor blk.24.attn_output.weight
create_tensor: loading tensor blk.24.ffn_norm.weight
create_tensor: loading tensor blk.24.ffn_gate.weight
create_tensor: loading tensor blk.24.ffn_down.weight
create_tensor: loading tensor blk.24.ffn_up.weight
create_tensor: loading tensor blk.25.attn_norm.weight
create_tensor: loading tensor blk.25.attn_q.weight
create_tensor: loading tensor blk.25.attn_k.weight
create_tensor: loading tensor blk.25.attn_v.weight
create_tensor: loading tensor blk.25.attn_output.weight
create_tensor: loading tensor blk.25.ffn_norm.weight
create_tensor: loading tensor blk.25.ffn_gate.weight
create_tensor: loading tensor blk.25.ffn_down.weight

In [ ]:
start = time.time()

response = llm.create_chat_completion(
    messages=[
        {
            "role": "user",
            "content": "What is Retrieval-Augmented Generation?"
        }
    ],
    max_tokens=100,
    temperature=0
)

print(response["choices"][0]["message"]["content"])

print("\nTime:", round(time.time() - start, 2), "seconds")

Llama.generate: Context reset requested or no prefix match. Cleared KV cache.
llama_perf_context_print:        load time =     365.61 ms
llama_perf_context_print: prompt eval time =     357.56 ms /    19 tokens (   18.82 ms per token,    53.14 tokens per second)
llama_perf_context_print:        eval time =    2735.73 ms /    99 runs   (   27.63 ms per token,    36.19 tokens per second)
llama_perf_context_print:       total time =    3144.25 ms /   118 tokens
llama_perf_context_print:    graphs reused =         98

Retrieval-Augmented Generation (RAG) is a method that combines the strengths of both Retrieval and Generation processes. It leverages the ability of Retrieval to pull relevant information from a database or the web, and the capability of Generation to create new content. The integration of these two processes allows for a more nuanced and contextually appropriate output. This approach is particularly useful in scenarios where the information to be generated is complex or requires a deep understanding of a specific

Time: 3.15 seconds

In [ ]:
!nvidia-smi

Wed Sep 23 17:42:07 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   51C    P0             28W /   70W |    4839MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A            2261      C   /usr/bin/python3                       4836MiB |
+-----------------------------------------------------------------------------------------+

In [ ]:
del llm

import gc
gc.collect()

~llama_context:      CUDA0 compute buffer size is 112.0117 MiB, matches expectation of 112.0117 MiB
~llama_context:  CUDA_Host compute buffer size is  24.0137 MiB, matches expectation of  24.0137 MiB

271

In [ ]:
PROMETHEUS_GGUF = "/content/prometheus-7b-v2.0.Q4_K_M.gguf"

In [ ]:
from openai import AsyncOpenAI

client = AsyncOpenAI(
    api_key="ollama",
    base_url="http://localhost:8000/v1",
)

In [ ]:
!pip install -q \
    "uvicorn>=0.22.0" \
    "fastapi>=0.100.0" \
    "pydantic-settings>=2.0.1" \
    "sse-starlette>=1.6.1" \
    "starlette-context>=0.3.6,<0.4" \
    "PyYAML>=5.1"

In [ ]:
!pkill -f "llama_cpp.server" || true

^C

In [ ]:
import subprocess
import time

server_log = open("/content/llama_server.log", "w")

server = subprocess.Popen(
    [
        "python",
        "-m",
        "llama_cpp.server",
        "--model", LOCAL_PROMETHEUS,
        "--model_alias", "prometheus",
        "--n_gpu_layers", "-1",
        "--n_ctx", "4096",
        "--host", "127.0.0.1",
        "--port", "8000"
    ],
    stdout=server_log,
    stderr=subprocess.STDOUT
)

time.sleep(8)

print("Server PID:", server.poll())

Server PID: None

In [ ]:
with open("/content/llama_server.log", "r") as f:
    print(f.read()[-5000:])

t: causal_attn   = 1
llama_context: flash_attn    = auto
llama_context: kv_unified    = true
llama_context: freq_base     = 1000000.0
llama_context: freq_scale    = 1
llama_context: n_ctx_seq (4096) < n_ctx_train (32768) -- the full capacity of the model will not be utilized
set_abort_callback: call
llama_context:  CUDA_Host  output buffer size =     0.12 MiB
llama_kv_cache: layer   0: dev = CUDA0
llama_kv_cache: layer   1: dev = CUDA0
llama_kv_cache: layer   2: dev = CUDA0
llama_kv_cache: layer   3: dev = CUDA0
llama_kv_cache: layer   4: dev = CUDA0
llama_kv_cache: layer   5: dev = CUDA0
llama_kv_cache: layer   6: dev = CUDA0
llama_kv_cache: layer   7: dev = CUDA0
llama_kv_cache: layer   8: dev = CUDA0
llama_kv_cache: layer   9: dev = CUDA0
llama_kv_cache: layer  10: dev = CUDA0
llama_kv_cache: layer  11: dev = CUDA0
llama_kv_cache: layer  12: dev = CUDA0
llama_kv_cache: layer  13: dev = CUDA0
llama_kv_cache: layer  14: dev = CUDA0
llama_kv_cache: layer  15: dev = CUDA0
llama_kv_cache: layer  16: dev = CUDA0
llama_kv_cache: layer  17: dev = CUDA0
llama_kv_cache: layer  18: dev = CUDA0
llama_kv_cache: layer  19: dev = CUDA0
llama_kv_cache: layer  20: dev = CUDA0
llama_kv_cache: layer  21: dev = CUDA0
llama_kv_cache: layer  22: dev = CUDA0
llama_kv_cache: layer  23: dev = CUDA0
llama_kv_cache: layer  24: dev = CUDA0
llama_kv_cache: layer  25: dev = CUDA0
llama_kv_cache: layer  26: dev = CUDA0
llama_kv_cache: layer  27: dev = CUDA0
llama_kv_cache: layer  28: dev = CUDA0
llama_kv_cache: layer  29: dev = CUDA0
llama_kv_cache: layer  30: dev = CUDA0
llama_kv_cache: layer  31: dev = CUDA0
llama_kv_cache:      CUDA0 KV buffer size =   512.00 MiB
llama_kv_cache: size =  512.00 MiB (  4096 cells,  32 layers,  1/1 seqs), K (f16):  256.00 MiB, V (f16):  256.00 MiB
llama_kv_cache: attn_rot_k = 0, n_embd_head_k_all = 128
llama_kv_cache: attn_rot_v = 0, n_embd_head_k_all = 128
llama_context: enumerating backends
llama_context: backend_ptrs.size() = 2
sched_reserve: reserving ...
sched_reserve: max_nodes = 2328
sched_reserve: reserving full memory module
sched_reserve: worst-case: n_tokens = 512, n_seqs = 1, n_outputs = 1
graph_reserve: reserving a graph for ubatch with n_tokens =    1, n_seqs =  1, n_outputs =    1
sched_reserve: Flash Attention was auto, set to enabled
sched_reserve: resolving fused Gated Delta Net support:
graph_reserve: reserving a graph for ubatch with n_tokens =    1, n_seqs =  1, n_outputs =    1
sched_reserve: fused Gated Delta Net (autoregressive) enabled
graph_reserve: reserving a graph for ubatch with n_tokens =   16, n_seqs =  1, n_outputs =   16
sched_reserve: fused Gated Delta Net (chunked) enabled
graph_reserve: reserving a graph for ubatch with n_tokens =  512, n_seqs =  1, n_outputs =  512
graph_reserve: reserving a graph for ubatch with n_tokens =    1, n_seqs =  1, n_outputs =    1
graph_reserve: reserving a graph for ubatch with n_tokens =  512, n_seqs =  1, n_outputs =  512
sched_reserve:      CUDA0 compute buffer size =   112.01 MiB
sched_reserve:  CUDA_Host compute buffer size =    24.01 MiB
sched_reserve: graph nodes  = 999
sched_reserve: graph splits = 2
sched_reserve: reserve took 17.41 ms, sched copies = 1
Llama.__init__: swa_full is not supported by this model, it will be disabled
CUDA : ARCHS = 750,800,860,870,890,900,1000,1200 | FORCE_MMQ = 1 | USE_GRAPHS = 1 | PEER_MAX_BATCH_SIZE = 128 | CPU : SSE3 = 1 | SSSE3 = 1 | BMI2 = 1 | LLAMAFILE = 1 | OPENMP = 1 | REPACK = 1 |
Model metadata: {'tokenizer.chat_template': "{{ bos_token }}{% for message in messages %}{% if (message['role'] == 'user') != (loop.index0 % 2 == 0) %}{{ raise_exception('Conversation roles must alternate user/assistant/user/assistant/...') }}{% endif %}{% if message['role'] == 'user' %}{{ '[INST] ' + message['content'] + ' [/INST]' }}{% elif message['role'] == 'assistant' %}{{ message['content'] + eos_token}}{% else %}{{ raise_exception('Only user and assistant roles are supported!') }}{% endif %}{% endfor %}", 'tokenizer.ggml.padding_token_id': '2', 'tokenizer.ggml.unknown_token_id': '0', 'tokenizer.ggml.eos_token_id': '2', 'general.quantization_version': '2', 'tokenizer.ggml.model': 'llama', 'general.architecture': 'llama', 'llama.rope.freq_base': '1000000.000000', 'tokenizer.ggml.pre': 'default', 'llama.context_length': '32768', 'general.name': 'prometheus-7b-v2.0', 'llama.embedding_length': '4096', 'llama.feed_forward_length': '14336', 'llama.attention.layer_norm_rms_epsilon': '0.000010', 'tokenizer.ggml.bos_token_id': '1', 'llama.attention.head_count': '32', 'llama.block_count': '32', 'llama.attention.head_count_kv': '8', 'general.file_type': '15', 'llama.vocab_size': '32000', 'llama.rope.dimension_count': '128'}
Available chat formats from metadata: chat_template.default
Guessed chat format: mistral-instruct
INFO:     Started server process [19484]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)

In [ ]:
!curl http://127.0.0.1:8000/v1/models

{"object":"list","data":[{"id":"prometheus","object":"model","owned_by":"me","permissions":[]}]}

In [ ]:
response = await client.chat.completions.create(
    model="prometheus",
    messages=[
        {
            "role": "user",
            "content": "What is Retrieval-Augmented Generation?"
        }
    ],
    temperature=0,
    max_tokens=100,
)

print(response.choices[0].message.content)

InternalServerError: Error code: 500 - {'error': {'message': '2 validation errors:\n  {\'type\': \'missing\', \'loc\': (\'response\', \'CreateChatCompletionResponse\', \'choices\', 0, \'message\', \'refusal\'), \'msg\': \'Field required\', \'input\': {\'role\': \'assistant\', \'content\': \'Retrieval-Augmented Generation (RAG) is a method that combines the strengths of both retrieval and generation processes. It involves using information from external sources to enhance the quality of generated content. This approach allows for more accurate and contextually relevant responses, as it leverages existing knowledge bases or databases to inform the generation process. The integration of retrieval with generation is a significant advancement in the field of natural language processing, as it enables systems to provide more nuanced\'}}\n  {\'type\': \'string_type\', \'loc\': (\'response\', \'str\'), \'msg\': \'Input should be a valid string\', \'input\': {\'id\': \'chatcmpl-ab0003e7-ea6d-4b0a-abc2-75ddd4e4d6b9\', \'object\': \'chat.completion\', \'created\': 1790185803, \'model\': \'prometheus\', \'choices\': [{\'index\': 0, \'message\': {\'role\': \'assistant\', \'content\': \'Retrieval-Augmented Generation (RAG) is a method that combines the strengths of both retrieval and generation processes. It involves using information from external sources to enhance the quality of generated content. This approach allows for more accurate and contextually relevant responses, as it leverages existing knowledge bases or databases to inform the generation process. The integration of retrieval with generation is a significant advancement in the field of natural language processing, as it enables systems to provide more nuanced\'}, \'logprobs\': None, \'finish_reason\': \'length\'}], \'usage\': {\'prompt_tokens\': 19, \'completion_tokens\': 100, \'total_tokens\': 119}}}\n\n  File "/usr/local/lib/python3.13/dist-packages/llama_cpp/server/app.py", line 376, in create_chat_completion\n    POST /v1/chat/completions', 'type': 'internal_server_error', 'param': None, 'code': None}}

In [ ]:
import inspect
from pathlib import Path
import llama_cpp.llama_chat_format as chat_format

file_path = Path(inspect.getfile(chat_format))

print(file_path)

/usr/local/lib/python3.13/dist-packages/llama_cpp/llama_chat_format.py

In [ ]:
text = file_path.read_text()

old = '"content": completion["choices"][0]["text"],\n'

new = (
    '"content": completion["choices"][0]["text"],\n'
    '"refusal": None,\n'
)

print("Occurrences:", text.count(old))

if old in text:
    text = text.replace(old, new, 1)
    file_path.write_text(text)
    print("Patch applied ✅")
else:
    print("Target line not found")

Occurrences: 1
Patch applied ✅

In [ ]:
!pkill -f "llama_cpp.server" || true

^C

In [ ]:
server = subprocess.Popen(
    [
        "python",
        "-m",
        "llama_cpp.server",
        "--model", LOCAL_PROMETHEUS,
        "--model_alias", "prometheus",
        "--n_gpu_layers", "-1",
        "--n_ctx", "4096",
        "--host", "127.0.0.1",
        "--port", "8000"
    ],
    stdout=server_log,
    stderr=subprocess.STDOUT
)

time.sleep(8)

print("Server PID:", server.poll())

Server PID: None

In [ ]:
response = await client.chat.completions.create(
    model="prometheus",
    messages=[
        {
            "role": "user",
            "content": "What is Retrieval-Augmented Generation?"
        }
    ],
    temperature=0,
    max_tokens=100,
)

print(response.choices[0].message.content)

Retrieval-Augmented Generation (RAG) is a method that combines the strengths of both retrieval and generation processes. It involves using information from external sources to enhance the quality of generated content. This approach allows for more accurate and contextually relevant responses, as it leverages existing knowledge bases or databases to inform the generation process. The integration of retrieval with generation is a significant advancement in the field of natural language processing, as it enables systems to provide more nuanced

# Project in my style starts from here

In [ ]:
!pip install -q \
    ragas==0.4.3 \
    "langchain-community==0.4.1" \
    openai \
    sentence-transformers

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 466.5/466.5 kB 40.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 105.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.5/45.5 kB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 68.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.4/69.4 kB 8.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 8.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 269.4/269.4 kB 26.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 353.2/353.2 kB 35.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.4/127.4 kB 9.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 572.1/572.1 kB 40.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 75.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 5.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.7/135.7 kB 15.6 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.

In [ ]:
PROMETHEUS_PATH = "/content/drive/MyDrive/RAG_Project/models/prometheus-7b-v2.0"
BGE_PATH = "/content/drive/MyDrive/RAG_Project/models/bge-base-en-v1.5"

In [ ]:
from openai import AsyncOpenAI

client = AsyncOpenAI(
    api_key="ollama",
    base_url="http://localhost:8000/v1",
)

In [ ]:
from ragas.llms import llm_factory

evaluator_llm = llm_factory(
    "prometheus",
    client=client,
    provider="openai"
)

In [ ]:
from ragas.embeddings import HuggingFaceEmbeddings

ragas_embeddings = HuggingFaceEmbeddings(
    model=BGE_PATH,
    use_api=False
)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

In [ ]:
from ragas.metrics.collections import (
    Faithfulness,
    AnswerRelevancy,
    ContextPrecision,
    ContextRecall,
)

faithfulness = Faithfulness(
    llm=evaluator_llm
)

answer_relevancy = AnswerRelevancy(
    llm=evaluator_llm,
    embeddings=ragas_embeddings
)

context_precision = ContextPrecision(
    llm=evaluator_llm
)

context_recall = ContextRecall(
    llm=evaluator_llm
)

In [ ]:
import json

EXPERIMENT_FILE = "/content/drive/MyDrive/RAG_Project/data/experiments.json"

with open(EXPERIMENT_FILE, "r", encoding="utf-8") as f:
    all_exp = json.load(f)

print(all_exp.keys())

dict_keys(['emb_a_semantic', 'emb_b_semantic', 'emb_a_recursive', 'emb_b_recursive'])

In [ ]:
import pandas as pd

In [ ]:
GT_FILE = "/content/drive/MyDrive/RAG_Project/data/rag_eval_qa_dataset.csv"

que = pd.read_csv(GT_FILE)

que.head()

,id,question,ground_truth_answer,source_document,topic,difficulty,question_type
0,q01,"When was ChatGPT launched, and which underlyin...","ChatGPT launched on November 30, 2022. It is p...",LLM_survey.pdf,model timeline,easy,factual
1,q02,How many parameters does the flagship GPT-3 mo...,175 billion parameters. GPT-3 is considered th...,LLM_survey.pdf,scaling / emergent abilities,easy,numeric
2,q03,What are the three LLM families the survey foc...,"GPT (released by OpenAI), LLaMA (released by M...",LLM_survey.pdf,LLM families,easy,factual
3,q04,What three emergent abilities does the survey ...,"In-context learning, instruction following, an...",LLM_survey.pdf,emergent abilities,medium,factual
4,q05,What are the three architectural categories us...,"Encoder-only (e.g., BERT), decoder-only (e.g.,...",LLM_survey.pdf,model architecture,easy,factual

In [ ]:
selected_question_ids = [
    "q01", "q03", "q13", "q21", "q02",
    "q19", "q25", "q30", "q43", "q33",
    "q14", "q27", "q48", "q04", "q16",
    "q17", "q37", "q07", "q23", "q12"
]

selected_questions = que[que['id'].isin(selected_question_ids)]['question'].to_list()

In [ ]:
ground_truth = que[que['id'].isin(selected_question_ids)]['ground_truth_answer'].to_list()

In [ ]:
for experiment_name, results in all_exp.items():
  for result, gt in zip(results, ground_truth):
    result["ground_truth"] = gt

In [ ]:
all_exp['emb_a_recursive'][0].keys()

dict_keys(['question', 'context', 'answer', 'ground_truth'])

In [ ]:
experiments = {
    "emb_a_semantic": all_exp["emb_a_semantic"],
    "emb_b_semantic": all_exp["emb_b_semantic"],
    "emb_a_recursive": all_exp["emb_a_recursive"],
    "emb_b_recursive": all_exp["emb_b_recursive"]
}

# Checking Time to process one sample

In [ ]:
sample = experiments["emb_a_semantic"][0]

print(sample)

{'question': 'When was ChatGPT launched, and which underlying model powers it?', 'context': ['(2023) demonstrate that ChatGPT achieves\n2https://www.wikidata.org/wiki/Wikidata:Main_Page\n10', 'regressions on public NLP datasets. The most important milestone of LLM development is the\nlaunch of ChatGPT (Chat Generative Pre-trained Transformer)\n[60] on November 30, 2022. ChatGPT is chatbot that enables\nusers to steer a conversation to complete a wide range of\ntasks such as question answering, information seeking, text\nsummarization, and more. ChatGPT is powered by GPT-3.5\n(and later by GPT-4), a sibling model to InstructGPT, which\nis trained to follow an instruction in a prompt and provide a\ndetailed response. GPT-4 [33] is the latest and most powerful LLM in the\nGPT family. Launched in March, 2023, GPT-4 is a multi-\nmodal LLM in that it can take image and text as inputs and\nproduce text outputs. While still less capable than humans\nin some of the most challenging real-world scenarios, GPT-4\nexhibits human-level performance on various professional and\nacademic benchmarks, including passing a simulated bar exam\nwith a score around the top 10% of test takers, as shown in\nFig 11. Like early GPT models, GPT-4 was first pre-trained to\npredict next tokens on large text corpora, and then fine-tuned\nwith RLHF to align model behaviors with human-desired ones. 2) The LLaMA F amily: LLaMA is a collection of founda-\ntion language models, released by Meta. Unlike GPT models,\nLLaMA models are open-source, i.e., model weights are\nreleased to the research community under a noncommercial\nlicense. Thus, the LLaMA family grows rapidly as these\nmodels are widely used by many research groups to develop\nbetter open-source LLMs to compete the closed-source ones or\nto develop task-specific LLMs for mission-critical applications. The first set of LLaMA models [32] was released in Febru-\nary 2023, ranging from 7B to 65B parameters. These models\nare pre-trained on trillions of tokens, collected from publicly\navailable datasets. LLaMA uses the transformer architecture of\nGPT-3, with a few minor architectural modifications, including\n(1) using a SwiGLU activation function instead of ReLU,\n(2) using rotary positional embeddings instead of absolute\npositional embedding, and (3) using root-mean-squared layer-\nnormalization instead of standard layer-normalization. The\nopen-source LLaMA-13B model outperforms the proprietary\nGPT-3 (175B) model on most benchmarks, making it a good\nbaseline for LLM research. In July 2023, Meta, in partnership with Microsoft, released\nthe LLaMA-2 collection [61], which include both foundation\nlanguage models and Chat models finetuned for dialog, known\nas LLaMA-2 Chat. The LLaMA-2 Chat models were reported\nto outperform other open-source models on many public\nbenchmarks. Fig 12 shows the training process of LLaMA-2\nChat. The process begins with pre-training LLaMA-2 using\npublicly available online data. Then, an initial version of\nLLaMA-2 Chat is built via supervised fine-tuning. Subse-\nquently, the model is iteratively refined using RLHF, rejection\nsampling and proximal policy optimization. In the RLHF stage,\nthe accumulation of human feedback for revising the reward\nmodel is crucial to prevent the reward model from being\nchanged too much, which could hurt the stability of LLaMA\nmodel training. Alpaca [62] is fine-tuned from the LLaMA-7B model using\n52K instruction-following demonstrations generated in the\nstyle of self-instruct using GPT-3.5 (text-davinci-003).', 'Moreover, Dai et al. (2023) find ChatGPT can provide effective essay feedback to students with good readability\nand high agreement with experts. 6.3 Legislation\nLLMs also empower legislation.'], 'answer': 'ChatGPT was launched on November 30, 2022. It is powered by the GPT-3.5 model (and later by GPT-4).', 'ground_truth': 'ChatGPT launched on November 30, 2022. It is powered by GPT-3.5 (and later GPT-4), a sibling model to InstructGPT.'}

In [ ]:
from ragas import Dataset as RagasDataset

test_dataset = RagasDataset(
    name="test_dataset",
    backend="local/csv",
    root_dir="."
)

test_dataset.append(sample)

test_dataset.save()

In [ ]:
from openai import AsyncOpenAI

client = AsyncOpenAI(
    api_key="anything",
    base_url="http://localhost:8000/v1",
)

In [ ]:
from ragas.llms import llm_factory

evaluator_llm = llm_factory(
    "prometheus",
    client=client,
    provider="openai"
)

In [ ]:
from ragas.embeddings import HuggingFaceEmbeddings

ragas_embeddings = HuggingFaceEmbeddings(
    model=BGE_PATH,
    use_api=False
)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

In [ ]:
from ragas.metrics.collections import (
    Faithfulness,
    AnswerRelevancy,
    ContextPrecision,
    ContextRecall
)

faithfulness = Faithfulness(
    llm=evaluator_llm
)

answer_relevancy = AnswerRelevancy(
    llm=evaluator_llm,
    embeddings=ragas_embeddings
)

context_precision = ContextPrecision(
    llm=evaluator_llm
)

context_recall = ContextRecall(
    llm=evaluator_llm
)

In [ ]:
from ragas import experiment

@experiment()
async def evaluate_rag(row):

    # 1. Faithfulness
    faithfulness_result = await faithfulness.ascore(
        user_input=row["question"],
        response=row["answer"],
        retrieved_contexts=row["context"],
    )

    # 2. Answer Relevancy
    answer_relevancy_result = await answer_relevancy.ascore(
        user_input=row["question"],
        response=row["answer"],
    )

    # 3. Context Precision
    context_precision_result = await context_precision.ascore(
        user_input=row["question"],
        retrieved_contexts=row["context"],
        reference=row["ground_truth"],
    )

    # 4. Context Recall
    context_recall_result = await context_recall.ascore(
        user_input=row["question"],
        retrieved_contexts=row["context"],
        reference=row["ground_truth"],
    )

    return {
        **row,
        "faithfulness": faithfulness_result.value,
        "answer_relevancy": answer_relevancy_result.value,
        "context_precision": context_precision_result.value,
        "context_recall": context_recall_result.value,
    }

In [ ]:
import time

start = time.time()

result1 = await evaluate_rag.arun(test_dataset)

print("Total Time:", round(time.time() - start, 2), "seconds")

Running experiment:   0%|          | 0/1 [00:00<?, ?it/s]ERROR:instructor.v2.retry:API call failed on attempt 1: Connection error.
ERROR:instructor.v2.retry:Max retries exceeded. Total attempts: 1, Last error: Connection error.
Running experiment: 100%|██████████| 1/1 [00:01<00:00,  1.47s/it]

Warning: Task failed with error: Connection error.
Total Time: 1.48 seconds

In [ ]:
result1.to_pandas()

Empty DataFrame
Columns: []
Index: []

# Checking llama-cpp Server

In [ ]:
!curl http://127.0.0.1:8000/v1/models

curl: (7) Failed to connect to 127.0.0.1 port 8000 after 0 ms: Couldn't connect to server

# If Server Not Running the Run this cell below

In [ ]:
import os
import shutil
import subprocess
import time

PROMETHEUS_GGUF = "/content/drive/MyDrive/RAG_Project/models/prometheus-7b-v2.0-GGUF/prometheus-7b-v2.0.Q4_K_M.gguf"

LOCAL_PROMETHEUS = "/content/prometheus-7b-v2.0.Q4_K_M.gguf"

if not os.path.exists(LOCAL_PROMETHEUS):
    print("Copying Prometheus...")
    shutil.copy2(PROMETHEUS_GGUF, LOCAL_PROMETHEUS)
    print("Copy complete ✅")
else:
    print("Model already exists locally ✅")

Copying Prometheus...
Copy complete ✅

In [ ]:
BGE_LOCAL = "/content/bge-base-en-v1.5"

In [ ]:
import os
import shutil

if not os.path.exists(BGE_LOCAL):
    print("Copying BGE...")
    shutil.copytree(BGE_PATH, BGE_LOCAL)
    print("BGE copy complete ✅")
else:
    print("BGE already exists locally ✅")

Copying BGE...
BGE copy complete ✅

In [ ]:
import subprocess
import sys
import time

!pkill -f "llama_cpp.server" || true

^C

In [ ]:
%pip install -q nvidia-cublas

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 439.3/439.3 MB 3.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.3/53.3 MB 22.3 MB/s eta 0:00:00

In [ ]:
%pip install -q nvidia-cuda-runtime==13.0.96

In [ ]:
%pip install -q --no-deps \
https://github.com/JamePeng/llama-cpp-python/releases/download/v0.3.38-cu130-Basic-linux-20260504/llama_cpp_python-0.3.38+cu130.basic-cp313-cp313-linux_x86_64.whl

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.5/469.5 MB 3.1 MB/s eta 0:00:00

In [ ]:
%pip install -q sse-starlette

In [ ]:
%pip install -q "starlette-context<0.4"

In [ ]:
!find /usr/local -name "libcudart.so*" 2>/dev/null | head -20

/usr/local/lib/python3.13/dist-packages/nvidia/cuda_runtime/lib/libcudart.so.12
/usr/local/lib/python3.13/dist-packages/nvidia/cu13/lib/libcudart.so.13
/usr/local/cuda-12.8/targets/x86_64-linux/lib/libcudart.so.12.8.90
/usr/local/cuda-12.8/targets/x86_64-linux/lib/libcudart.so.12
/usr/local/cuda-12.8/targets/x86_64-linux/lib/libcudart.so

In [ ]:
import os

cuda_lib = "/usr/local/lib/python3.13/dist-packages/nvidia/cu13/lib"

os.environ["LD_LIBRARY_PATH"] = (
    cuda_lib + ":" + os.environ.get("LD_LIBRARY_PATH", "")
)

print(cuda_lib)

/usr/local/lib/python3.13/dist-packages/nvidia/cu13/lib

In [ ]:
import os

print(
    os.path.exists(
        os.path.join(cuda_lib, "libcudart.so.13")
    )
)

True

In [ ]:
import ctypes

ctypes.CDLL(
    "/usr/local/lib/python3.13/dist-packages/nvidia/cu13/lib/libcudart.so.13",
    mode=ctypes.RTLD_GLOBAL
)

print("CUDA runtime loaded ✅")

CUDA runtime loaded ✅

In [ ]:
import glob

cublas_files = glob.glob(
    "/usr/local/lib/python3.13/dist-packages/nvidia/**/libcublas.so.13",
    recursive=True
)

print(cublas_files)

['/usr/local/lib/python3.13/dist-packages/nvidia/cu13/lib/libcublas.so.13']

In [ ]:
import ctypes

ctypes.CDLL(
    cublas_files[0],
    mode=ctypes.RTLD_GLOBAL
)

print("cuBLAS loaded ✅")

cuBLAS loaded ✅

In [ ]:
from llama_cpp import Llama

print("llama_cpp ready ✅")

llama_cpp ready ✅

In [ ]:
import os
import subprocess
import sys
import time

CUDA_LIB = "/usr/local/lib/python3.13/dist-packages/nvidia/cu13/lib"

os.environ["LD_LIBRARY_PATH"] = (
    CUDA_LIB + ":" + os.environ.get("LD_LIBRARY_PATH", "")
)

print("CUDA path set ✅")

CUDA path set ✅

In [ ]:
PROMETHEUS_GGUF = "/content/prometheus-7b-v2.0.Q4_K_M.gguf"

server_log = open("/content/llama_server.log", "w")

server = subprocess.Popen(
    [
        sys.executable,
        "-m",
        "llama_cpp.server",
        "--model", PROMETHEUS_GGUF,
        "--model_alias", "prometheus",
        "--n_gpu_layers", "-1",
        "--n_ctx", "4096",
        "--host", "127.0.0.1",
        "--port", "8000"
    ],
    stdout=server_log,
    stderr=subprocess.STDOUT,
    env=os.environ.copy()
)

time.sleep(8)

print("Server status:", server.poll())

Server status: None

In [ ]:
!curl http://127.0.0.1:8000/v1/models

curl: (7) Failed to connect to 127.0.0.1 port 8000 after 0 ms: Couldn't connect to server

In [ ]:
server_log.flush()

with open("/content/llama_server.log", "r") as f:
    print(f.read()[-10000:])

fn_up.weight
create_tensor: loading tensor blk.23.attn_norm.weight
create_tensor: loading tensor blk.23.attn_q.weight
create_tensor: loading tensor blk.23.attn_k.weight
create_tensor: loading tensor blk.23.attn_v.weight
create_tensor: loading tensor blk.23.attn_output.weight
create_tensor: loading tensor blk.23.ffn_norm.weight
create_tensor: loading tensor blk.23.ffn_gate.weight
create_tensor: loading tensor blk.23.ffn_down.weight
create_tensor: loading tensor blk.23.ffn_up.weight
create_tensor: loading tensor blk.24.attn_norm.weight
create_tensor: loading tensor blk.24.attn_q.weight
create_tensor: loading tensor blk.24.attn_k.weight
create_tensor: loading tensor blk.24.attn_v.weight
create_tensor: loading tensor blk.24.attn_output.weight
create_tensor: loading tensor blk.24.ffn_norm.weight
create_tensor: loading tensor blk.24.ffn_gate.weight
create_tensor: loading tensor blk.24.ffn_down.weight
create_tensor: loading tensor blk.24.ffn_up.weight
create_tensor: loading tensor blk.25.attn_norm.weight
create_tensor: loading tensor blk.25.attn_q.weight
create_tensor: loading tensor blk.25.attn_k.weight
create_tensor: loading tensor blk.25.attn_v.weight
create_tensor: loading tensor blk.25.attn_output.weight
create_tensor: loading tensor blk.25.ffn_norm.weight
create_tensor: loading tensor blk.25.ffn_gate.weight
create_tensor: loading tensor blk.25.ffn_down.weight
create_tensor: loading tensor blk.25.ffn_up.weight
create_tensor: loading tensor blk.26.attn_norm.weight
create_tensor: loading tensor blk.26.attn_q.weight
create_tensor: loading tensor blk.26.attn_k.weight
create_tensor: loading tensor blk.26.attn_v.weight
create_tensor: loading tensor blk.26.attn_output.weight
create_tensor: loading tensor blk.26.ffn_norm.weight
create_tensor: loading tensor blk.26.ffn_gate.weight
create_tensor: loading tensor blk.26.ffn_down.weight
create_tensor: loading tensor blk.26.ffn_up.weight
create_tensor: loading tensor blk.27.attn_norm.weight
create_tensor: loading tensor blk.27.attn_q.weight
create_tensor: loading tensor blk.27.attn_k.weight
create_tensor: loading tensor blk.27.attn_v.weight
create_tensor: loading tensor blk.27.attn_output.weight
create_tensor: loading tensor blk.27.ffn_norm.weight
create_tensor: loading tensor blk.27.ffn_gate.weight
create_tensor: loading tensor blk.27.ffn_down.weight
create_tensor: loading tensor blk.27.ffn_up.weight
create_tensor: loading tensor blk.28.attn_norm.weight
create_tensor: loading tensor blk.28.attn_q.weight
create_tensor: loading tensor blk.28.attn_k.weight
create_tensor: loading tensor blk.28.attn_v.weight
create_tensor: loading tensor blk.28.attn_output.weight
create_tensor: loading tensor blk.28.ffn_norm.weight
create_tensor: loading tensor blk.28.ffn_gate.weight
create_tensor: loading tensor blk.28.ffn_down.weight
create_tensor: loading tensor blk.28.ffn_up.weight
create_tensor: loading tensor blk.29.attn_norm.weight
create_tensor: loading tensor blk.29.attn_q.weight
create_tensor: loading tensor blk.29.attn_k.weight
create_tensor: loading tensor blk.29.attn_v.weight
create_tensor: loading tensor blk.29.attn_output.weight
create_tensor: loading tensor blk.29.ffn_norm.weight
create_tensor: loading tensor blk.29.ffn_gate.weight
create_tensor: loading tensor blk.29.ffn_down.weight
create_tensor: loading tensor blk.29.ffn_up.weight
create_tensor: loading tensor blk.30.attn_norm.weight
create_tensor: loading tensor blk.30.attn_q.weight
create_tensor: loading tensor blk.30.attn_k.weight
create_tensor: loading tensor blk.30.attn_v.weight
create_tensor: loading tensor blk.30.attn_output.weight
create_tensor: loading tensor blk.30.ffn_norm.weight
create_tensor: loading tensor blk.30.ffn_gate.weight
create_tensor: loading tensor blk.30.ffn_down.weight
create_tensor: loading tensor blk.30.ffn_up.weight
create_tensor: loading tensor blk.31.attn_norm.weight
create_tensor: loading tensor blk.31.attn_q.weight
create_tensor: loading tensor blk.31.attn_k.weight
create_tensor: loading tensor blk.31.attn_v.weight
create_tensor: loading tensor blk.31.attn_output.weight
create_tensor: loading tensor blk.31.ffn_norm.weight
create_tensor: loading tensor blk.31.ffn_gate.weight
create_tensor: loading tensor blk.31.ffn_down.weight
create_tensor: loading tensor blk.31.ffn_up.weight
done_getting_tensors: tensor 'token_embd.weight' (q4_K) (and 0 others) cannot be used with preferred buffer type CUDA_Host, using CPU instead
load_tensors: offloading output layer to GPU
load_tensors: offloading 31 repeating layers to GPU
load_tensors: offloaded 33/33 layers to GPU
load_tensors:   CPU_Mapped model buffer size =    70.31 MiB
load_tensors:        CUDA0 model buffer size =  4095.05 MiB
.................................................................................................
llama_context: constructing llama_context
llama_context: n_seq_max     = 1
llama_context: n_ctx         = 4096
llama_context: n_ctx_seq     = 4096
llama_context: n_batch       = 512
llama_context: n_ubatch      = 512
llama_context: causal_attn   = 1
llama_context: flash_attn    = auto
llama_context: kv_unified    = true
llama_context: freq_base     = 1000000.0
llama_context: freq_scale    = 1
llama_context: n_ctx_seq (4096) < n_ctx_train (32768) -- the full capacity of the model will not be utilized
set_abort_callback: call
llama_context:  CUDA_Host  output buffer size =     0.12 MiB
llama_kv_cache: layer   0: dev = CUDA0
llama_kv_cache: layer   1: dev = CUDA0
llama_kv_cache: layer   2: dev = CUDA0
llama_kv_cache: layer   3: dev = CUDA0
llama_kv_cache: layer   4: dev = CUDA0
llama_kv_cache: layer   5: dev = CUDA0
llama_kv_cache: layer   6: dev = CUDA0
llama_kv_cache: layer   7: dev = CUDA0
llama_kv_cache: layer   8: dev = CUDA0
llama_kv_cache: layer   9: dev = CUDA0
llama_kv_cache: layer  10: dev = CUDA0
llama_kv_cache: layer  11: dev = CUDA0
llama_kv_cache: layer  12: dev = CUDA0
llama_kv_cache: layer  13: dev = CUDA0
llama_kv_cache: layer  14: dev = CUDA0
llama_kv_cache: layer  15: dev = CUDA0
llama_kv_cache: layer  16: dev = CUDA0
llama_kv_cache: layer  17: dev = CUDA0
llama_kv_cache: layer  18: dev = CUDA0
llama_kv_cache: layer  19: dev = CUDA0
llama_kv_cache: layer  20: dev = CUDA0
llama_kv_cache: layer  21: dev = CUDA0
llama_kv_cache: layer  22: dev = CUDA0
llama_kv_cache: layer  23: dev = CUDA0
llama_kv_cache: layer  24: dev = CUDA0
llama_kv_cache: layer  25: dev = CUDA0
llama_kv_cache: layer  26: dev = CUDA0
llama_kv_cache: layer  27: dev = CUDA0
llama_kv_cache: layer  28: dev = CUDA0
llama_kv_cache: layer  29: dev = CUDA0
llama_kv_cache: layer  30: dev = CUDA0
llama_kv_cache: layer  31: dev = CUDA0
llama_kv_cache:      CUDA0 KV buffer size =   512.00 MiB
llama_kv_cache: size =  512.00 MiB (  4096 cells,  32 layers,  1/1 seqs), K (f16):  256.00 MiB, V (f16):  256.00 MiB
llama_kv_cache: attn_rot_k = 0, n_embd_head_k_all = 128
llama_kv_cache: attn_rot_v = 0, n_embd_head_k_all = 128
llama_context: enumerating backends
llama_context: backend_ptrs.size() = 2
sched_reserve: reserving ...
sched_reserve: max_nodes = 2328
sched_reserve: reserving full memory module
sched_reserve: worst-case: n_tokens = 512, n_seqs = 1, n_outputs = 1
graph_reserve: reserving a graph for ubatch with n_tokens =    1, n_seqs =  1, n_outputs =    1
sched_reserve: Flash Attention was auto, set to enabled
sched_reserve: resolving fused Gated Delta Net support:
graph_reserve: reserving a graph for ubatch with n_tokens =    1, n_seqs =  1, n_outputs =    1
sched_reserve: fused Gated Delta Net (autoregressive) enabled
graph_reserve: reserving a graph for ubatch with n_tokens =   16, n_seqs =  1, n_outputs =   16
sched_reserve: fused Gated Delta Net (chunked) enabled
graph_reserve: reserving a graph for ubatch with n_tokens =  512, n_seqs =  1, n_outputs =  512
graph_reserve: reserving a graph for ubatch with n_tokens =    1, n_seqs =  1, n_outputs =    1
graph_reserve: reserving a graph for ubatch with n_tokens =  512, n_seqs =  1, n_outputs =  512
sched_reserve:      CUDA0 compute buffer size =   112.01 MiB
sched_reserve:  CUDA_Host compute buffer size =    24.01 MiB
sched_reserve: graph nodes  = 999
sched_reserve: graph splits = 2
sched_reserve: reserve took 24.43 ms, sched copies = 1
Llama.__init__: swa_full is not supported by this model, it will be disabled
CUDA : ARCHS = 750,800,860,870,890,900,1000,1200 | FORCE_MMQ = 1 | USE_GRAPHS = 1 | PEER_MAX_BATCH_SIZE = 128 | CPU : SSE3 = 1 | SSSE3 = 1 | BMI2 = 1 | LLAMAFILE = 1 | OPENMP = 1 | REPACK = 1 |
Model metadata: {'tokenizer.chat_template': "{{ bos_token }}{% for message in messages %}{% if (message['role'] == 'user') != (loop.index0 % 2 == 0) %}{{ raise_exception('Conversation roles must alternate user/assistant/user/assistant/...') }}{% endif %}{% if message['role'] == 'user' %}{{ '[INST] ' + message['content'] + ' [/INST]' }}{% elif message['role'] == 'assistant' %}{{ message['content'] + eos_token}}{% else %}{{ raise_exception('Only user and assistant roles are supported!') }}{% endif %}{% endfor %}", 'tokenizer.ggml.padding_token_id': '2', 'tokenizer.ggml.unknown_token_id': '0', 'tokenizer.ggml.eos_token_id': '2', 'general.quantization_version': '2', 'tokenizer.ggml.model': 'llama', 'general.architecture': 'llama', 'llama.rope.freq_base': '1000000.000000', 'tokenizer.ggml.pre': 'default', 'llama.context_length': '32768', 'general.name': 'prometheus-7b-v2.0', 'llama.embedding_length': '4096', 'llama.feed_forward_length': '14336', 'llama.attention.layer_norm_rms_epsilon': '0.000010', 'tokenizer.ggml.bos_token_id': '1', 'llama.attention.head_count': '32', 'llama.block_count': '32', 'llama.attention.head_count_kv': '8', 'general.file_type': '15', 'llama.vocab_size': '32000', 'llama.rope.dimension_count': '128'}
Available chat formats from metadata: chat_template.default
Guessed chat format: mistral-instruct
INFO:     Started server process [24490]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)

In [ ]:
print("Server status:", server.poll())

Server status: 1

In [ ]:
server_log.flush()

with open("/content/llama_server.log", "r") as f:
    print(f.read()[-12000:])

Traceback (most recent call last):
  File "<frozen runpy>", line 203, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.13/dist-packages/llama_cpp/server/__main__.py", line 33, in <module>
    from llama_cpp.server.app import create_app
  File "/usr/local/lib/python3.13/dist-packages/llama_cpp/server/app.py", line 21, in <module>
    from sse_starlette.sse import EventSourceResponse
ModuleNotFoundError: No module named 'sse_starlette'

In [ ]:
!curl http://127.0.0.1:8000/v1/models

{"object":"list","data":[{"id":"prometheus","object":"model","owned_by":"me","permissions":[]}]}

In [ ]:
from openai import AsyncOpenAI

client = AsyncOpenAI(
    api_key="anything",
    base_url="http://127.0.0.1:8000/v1"
)

In [ ]:
!pkill -f "llama_cpp.server" || true

^C

In [ ]:
import inspect
import llama_cpp.server.app as server_app

app_file = inspect.getfile(server_app)

print(app_file)

/usr/local/lib/python3.13/dist-packages/llama_cpp/server/app.py

In [ ]:
from pathlib import Path

path = Path(app_file)

text = path.read_text()

old = 'response_model=Union[llama_cpp.ChatCompletion, str],'
new = 'response_model=None,'

print("Found:", old in text)

text = text.replace(old, new, 1)

path.write_text(text)

print("Patch applied ✅")

Found: True
Patch applied ✅

In [ ]:
import subprocess
import sys
import time
import os

server_log = open("/content/llama_server.log", "w")

server = subprocess.Popen(
    [
        sys.executable,
        "-m",
        "llama_cpp.server",
        "--model", LOCAL_PROMETHEUS,
        "--model_alias", "prometheus",
        "--n_gpu_layers", "-1",
        "--n_ctx", "4096",
        "--host", "127.0.0.1",
        "--port", "8000"
    ],
    stdout=server_log,
    stderr=subprocess.STDOUT,
    env=os.environ.copy()
)

time.sleep(8)

print("Server status:", server.poll())

Server status: None

In [ ]:
!curl http://127.0.0.1:8000/v1/models

{"object":"list","data":[{"id":"prometheus","object":"model","owned_by":"me","permissions":[]}]}

In [ ]:
import requests

response = requests.get("http://127.0.0.1:8000/v1/models")

print(response.status_code)
print(response.json())

200
{'object': 'list', 'data': [{'id': 'prometheus', 'object': 'model', 'owned_by': 'me', 'permissions': []}]}

In [ ]:
from openai import AsyncOpenAI

client = AsyncOpenAI(
    api_key="anything",
    base_url="http://127.0.0.1:8000/v1"
)

In [ ]:
import time

start = time.time()

response = await client.chat.completions.create(
    model="prometheus",
    messages=[
        {
            "role": "user",
            "content": "What is Retrieval-Augmented Generation?"
        }
    ],
    temperature=0,
    max_tokens=100
)

print(response.choices[0].message.content)

print("\nTime:", round(time.time() - start, 2), "seconds")

Retrieval-Augmented Generation (RAG) is a method that combines the strengths of both retrieval and generation processes. It involves using information from external sources to enhance the quality of generated content. This approach allows for more accurate and contextually relevant responses, as it leverages existing knowledge bases or databases to inform the generation process. The integration of retrieval with generation is a significant advancement in the field of natural language processing, as it enables systems to provide more nuanced

Time: 2.84 seconds

In [ ]:
from ragas.llms import llm_factory

evaluator_llm = llm_factory(
    "prometheus",
    client=client,
    provider="openai"
)

In [ ]:
import os
import shutil

BGE_LOCAL = "/content/bge-base-en-v1.5"

if not os.path.exists(BGE_LOCAL):
    print("Copying BGE...")
    shutil.copytree(BGE_PATH, BGE_LOCAL)
    print("BGE copy complete ✅")
else:
    print("BGE already exists locally ✅")

BGE already exists locally ✅

In [ ]:
from ragas.embeddings import HuggingFaceEmbeddings

ragas_embeddings = HuggingFaceEmbeddings(
    model=BGE_LOCAL,
    use_api=False
)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

In [ ]:
from ragas.metrics.collections import (
    Faithfulness,
    AnswerRelevancy,
    ContextPrecision,
    ContextRecall
)

faithfulness = Faithfulness(
    llm=evaluator_llm
)

answer_relevancy = AnswerRelevancy(
    llm=evaluator_llm,
    embeddings=ragas_embeddings
)

context_precision = ContextPrecision(
    llm=evaluator_llm
)

context_recall = ContextRecall(
    llm=evaluator_llm
)

In [ ]:
sample = experiments["emb_a_semantic"][0]

print(sample.keys())

dict_keys(['question', 'context', 'answer', 'ground_truth'])

In [ ]:
import time

start = time.time()

faithfulness_result = await faithfulness.ascore(
    user_input=sample["question"],
    response=sample["answer"],
    retrieved_contexts=sample["context"]
)

print("Faithfulness:", faithfulness_result.value)
print("Time:", round(time.time() - start, 2), "seconds")

Faithfulness: 0.0
Time: 10.27 seconds

In [ ]:
import time

start = time.time()

answer_relevancy_result = await answer_relevancy.ascore(
    user_input=sample["question"],
    response=sample["answer"],
)

print("Answer Relevancy:", answer_relevancy_result.value)
print("Time:", round(time.time() - start, 2), "seconds")

Answer Relevancy: 0.9221417367845225
Time: 5.14 seconds

In [ ]:
start = time.time()

context_precision_result = await context_precision.ascore(
    user_input=sample["question"],
    retrieved_contexts=sample["context"],
    reference=sample["ground_truth"],
)

print("Context Precision:", context_precision_result.value)
print("Time:", round(time.time() - start, 2), "seconds")

Context Precision: 0.49999999995
Time: 10.41 seconds

In [ ]:
start = time.time()

context_recall_result = await context_recall.ascore(
    user_input=sample["question"],
    retrieved_contexts=sample["context"],
    reference=sample["ground_truth"],
)

print("Context Recall:", context_recall_result.value)
print("Time:", round(time.time() - start, 2), "seconds")

Context Recall: 1.0
Time: 8.32 seconds

In [ ]:
import json
import os

CHECKPOINT_FILE = "/content/drive/MyDrive/RAG_Project/data/ragas_checkpoint.json"

if os.path.exists(CHECKPOINT_FILE):
    with open(CHECKPOINT_FILE, "r", encoding="utf-8") as f:
        checkpoint = json.load(f)

    print("Existing checkpoint loaded ✅")

else:
    checkpoint = {}

    print("New checkpoint created ✅")

New checkpoint created ✅

In [ ]:
def save_checkpoint():

    with open(CHECKPOINT_FILE, "w", encoding="utf-8") as f:
        json.dump(
            checkpoint,
            f,
            indent=2,
            ensure_ascii=False
        )

In [ ]:
import time

metric_names = [
    "faithfulness",
    "answer_relevancy",
    "context_precision",
    "context_recall"
]

for experiment_name, rows in experiments.items():

    print(f"\n{'='*60}")
    print(f"Starting: {experiment_name}")
    print(f"{'='*60}")

    if experiment_name not in checkpoint:
        checkpoint[experiment_name] = {}

    for i, row in enumerate(rows):

        row_id = str(i)

        # Already completed row
        if (
            row_id in checkpoint[experiment_name]
            and all(
                metric in checkpoint[experiment_name][row_id]
                for metric in metric_names
            )
        ):
            print(
                f"{experiment_name} | "
                f"Q{i+1}/{len(rows)} | Already completed ✅"
            )
            continue

        if row_id not in checkpoint[experiment_name]:
            checkpoint[experiment_name][row_id] = {
                "question": row["question"]
            }

        result = checkpoint[experiment_name][row_id]

        print(
            f"\n{experiment_name} | "
            f"Q{i+1}/{len(rows)}"
        )

        # -------------------------
        # 1. Faithfulness
        # -------------------------
        if "faithfulness" not in result:

            start = time.time()

            score = await faithfulness.ascore(
                user_input=row["question"],
                response=row["answer"],
                retrieved_contexts=row["context"],
            )

            result["faithfulness"] = score.value

            save_checkpoint()

            print(
                "Faithfulness:",
                score.value,
                "|",
                round(time.time() - start, 2),
                "sec"
            )


        # -------------------------
        # 2. Answer Relevancy
        # -------------------------
        if "answer_relevancy" not in result:

            start = time.time()

            score = await answer_relevancy.ascore(
                user_input=row["question"],
                response=row["answer"],
            )

            result["answer_relevancy"] = score.value

            save_checkpoint()

            print(
                "Answer Relevancy:",
                score.value,
                "|",
                round(time.time() - start, 2),
                "sec"
            )


        # -------------------------
        # 3. Context Precision
        # -------------------------
        if "context_precision" not in result:

            start = time.time()

            score = await context_precision.ascore(
                user_input=row["question"],
                retrieved_contexts=row["context"],
                reference=row["ground_truth"],
            )

            result["context_precision"] = score.value

            save_checkpoint()

            print(
                "Context Precision:",
                score.value,
                "|",
                round(time.time() - start, 2),
                "sec"
            )


        # -------------------------
        # 4. Context Recall
        # -------------------------
        if "context_recall" not in result:

            start = time.time()

            score = await context_recall.ascore(
                user_input=row["question"],
                retrieved_contexts=row["context"],
                reference=row["ground_truth"],
            )

            result["context_recall"] = score.value

            save_checkpoint()

            print(
                "Context Recall:",
                score.value,
                "|",
                round(time.time() - start, 2),
                "sec"
            )


        print("✅ Row completed")

============================================================
Starting: emb_a_semantic
============================================================
emb_a_semantic | Q1/20 | Already completed ✅
emb_a_semantic | Q2/20 | Already completed ✅
emb_a_semantic | Q3/20 | Already completed ✅
emb_a_semantic | Q4/20 | Already completed ✅
emb_a_semantic | Q5/20 | Already completed ✅
emb_a_semantic | Q6/20 | Already completed ✅
emb_a_semantic | Q7/20 | Already completed ✅
emb_a_semantic | Q8/20 | Already completed ✅
emb_a_semantic | Q9/20 | Already completed ✅
emb_a_semantic | Q10/20 | Already completed ✅
emb_a_semantic | Q11/20 | Already completed ✅
emb_a_semantic | Q12/20 | Already completed ✅
emb_a_semantic | Q13/20 | Already completed ✅
emb_a_semantic | Q14/20 | Already completed ✅
emb_a_semantic | Q15/20 | Already completed ✅
emb_a_semantic | Q16/20 | Already completed ✅
emb_a_semantic | Q17/20 | Already completed ✅
emb_a_semantic | Q18/20 | Already completed ✅
emb_a_semantic | Q19/20 | Already completed ✅
emb_a_semantic | Q20/20 | Already completed ✅

============================================================
Starting: emb_b_semantic
============================================================
emb_b_semantic | Q1/20 | Already completed ✅
emb_b_semantic | Q2/20 | Already completed ✅
emb_b_semantic | Q3/20 | Already completed ✅
emb_b_semantic | Q4/20 | Already completed ✅
emb_b_semantic | Q5/20 | Already completed ✅
emb_b_semantic | Q6/20 | Already completed ✅
emb_b_semantic | Q7/20 | Already completed ✅
emb_b_semantic | Q8/20 | Already completed ✅
emb_b_semantic | Q9/20 | Already completed ✅
emb_b_semantic | Q10/20 | Already completed ✅
emb_b_semantic | Q11/20 | Already completed ✅
emb_b_semantic | Q12/20 | Already completed ✅
emb_b_semantic | Q13/20 | Already completed ✅
emb_b_semantic | Q14/20 | Already completed ✅
emb_b_semantic | Q15/20 | Already completed ✅
emb_b_semantic | Q16/20 | Already completed ✅
emb_b_semantic | Q17/20 | Already completed ✅
emb_b_semantic | Q18/20 | Already completed ✅
emb_b_semantic | Q19/20 | Already completed ✅
emb_b_semantic | Q20/20 | Already completed ✅

============================================================
Starting: emb_a_recursive
============================================================
emb_a_recursive | Q1/20 | Already completed ✅
emb_a_recursive | Q2/20 | Already completed ✅
emb_a_recursive | Q3/20 | Already completed ✅
emb_a_recursive | Q4/20 | Already completed ✅
emb_a_recursive | Q5/20 | Already completed ✅
emb_a_recursive | Q6/20 | Already completed ✅
emb_a_recursive | Q7/20 | Already completed ✅
emb_a_recursive | Q8/20 | Already completed ✅
emb_a_recursive | Q9/20 | Already completed ✅
emb_a_recursive | Q10/20 | Already completed ✅
emb_a_recursive | Q11/20 | Already completed ✅
emb_a_recursive | Q12/20 | Already completed ✅
emb_a_recursive | Q13/20 | Already completed ✅
emb_a_recursive | Q14/20 | Already completed ✅
emb_a_recursive | Q15/20 | Already completed ✅
emb_a_recursive | Q16/20 | Already completed ✅
emb_a_recursive | Q17/20 | Already completed ✅
emb_a_recursive | Q18/20 | Already completed ✅
emb_a_recursive | Q19/20 | Already completed ✅
emb_a_recursive | Q20/20 | Already completed ✅

============================================================
Starting: emb_b_recursive
============================================================
emb_b_recursive | Q1/20 | Already completed ✅
emb_b_recursive | Q2/20 | Already completed ✅
emb_b_recursive | Q3/20 | Already completed ✅
emb_b_recursive | Q4/20 | Already completed ✅
emb_b_recursive | Q5/20 | Already completed ✅

emb_b_recursive | Q6/20

IncompleteOutputException: The output is incomplete due to a max_tokens length limit.

In [ ]:
!pkill -f "llama_cpp.server" || true

^C

In [ ]:
import subprocess
import sys
import time
import os

server_log = open("/content/llama_server.log", "w")

server = subprocess.Popen(
    [
        sys.executable,
        "-m",
        "llama_cpp.server",
        "--model", LOCAL_PROMETHEUS,
        "--model_alias", "prometheus",
        "--n_gpu_layers", "-1",
        "--n_ctx", "8192",
        "--host", "127.0.0.1",
        "--port", "8000"
    ],
    stdout=server_log,
    stderr=subprocess.STDOUT,
    env=os.environ.copy()
)

time.sleep(8)

print("Server status:", server.poll())

Server status: None

In [ ]:
import requests

response = requests.get(
    "http://127.0.0.1:8000/v1/models"
)

print(response.status_code)
print(response.json())

200
{'object': 'list', 'data': [{'id': 'prometheus', 'object': 'model', 'owned_by': 'me', 'permissions': []}]}

In [ ]:
!ldd /usr/local/lib/python3.13/dist-packages/llama_cpp/lib/libggml.so | grep "not found"

In [ ]:
!ldd /usr/local/lib/python3.13/dist-packages/llama_cpp/lib/libggml.so | grep "not found"

	libcublas.so.13 => not found

In [ ]:
server_log = open("/content/llama_server.log", "w")

server = subprocess.Popen(
    [
        sys.executable,
        "-m",
        "llama_cpp.server",
        "--model", LOCAL_PROMETHEUS,
        "--model_alias", "prometheus",
        "--n_gpu_layers", "-1",
        "--n_ctx", "4096",
        "--host", "127.0.0.1",
        "--port", "8000"
    ],
    stdout=server_log,
    stderr=subprocess.STDOUT
)

time.sleep(8)

print("Server status:", server.poll())

Server status: 1

In [ ]:
!curl http://127.0.0.1:8000/v1/models

curl: (7) Failed to connect to 127.0.0.1 port 8000 after 0 ms: Couldn't connect to server

In [ ]:
print("Server status:", server.poll())

server_log.flush()

with open("/content/llama_server.log", "r") as f:
    print(f.read()[-10000:])

Server status: 1
/usr/bin/python3: Error while finding module specification for 'llama_cpp.server' (ModuleNotFoundError: No module named 'llama_cpp')

In [ ]:
!python -c "import llama_cpp; print(llama_cpp.__file__)"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
    import llama_cpp; print(llama_cpp.__file__)
    ^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'llama_cpp'

# Creating Comparison Table

In [ ]:
import pandas as pd
import json

RESULT_FILE = "/content/drive/MyDrive/RAG_Project/data/ragas_results_with_transparent_estimates.json"

with open(RESULT_FILE, "r") as f:
    results = json.load(f)

metrics = [
    "faithfulness",
    "answer_relevancy",
    "context_precision",
    "context_recall"
]

In [ ]:
clean_results = {}

for experiment, rows in results.items():

    if experiment.startswith("_"):
        continue

    clean_results[experiment] = pd.DataFrame(rows.values())[metrics]

In [ ]:
clean_results["emb_a_semantic"].head()

   faithfulness  answer_relevancy  context_precision  context_recall
0           0.0          0.922142           0.500000             1.0
1           1.0          0.817483           0.833333             1.0
2           1.0          0.000000           1.000000             1.0
3           0.0          0.972156           0.833333             1.0
4           0.0          0.000000           0.000000             0.0

In [ ]:
avg_df = pd.DataFrame({
    experiment: df.mean()
    for experiment, df in clean_results.items()
}).T

In [ ]:
avg_df.index.name = "Configuration"
avg_df = avg_df.reset_index()

avg_df.round(3)

,Configuration,faithfulness,answer_relevancy,context_precision,context_recall
0,emb_a_semantic,0.362,0.624,0.621,0.6
1,emb_b_semantic,0.325,0.634,0.700,0.6
2,emb_a_recursive,0.400,0.751,0.742,0.7
3,emb_b_recursive,0.275,0.757,0.808,0.7

### Based on the RAGAS evaluation, **all-MiniLM-L6-v2 + RecursiveCharacterTextSplitter** (emb_a_recursive) was selected as the final retrieval configuration because it provided the strongest overall balance across Faithfulness, Answer Relevancy, Context Precision, and Context Recall among the fully evaluated configurations.